#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : {{cookiecutter.project_name}}  # The title of the book. Will be placed in the left navbar.
author                      : {{cookiecutter.author}}  # The author of the book
copyright                   : "{{cookiecutter.year}}"  # Copyright year to be placed in the footer
logo                        : ./images/nd_logo.png  # A path to the book logo

# Linking
html:
  favicon: ./images/nd_logo_small.png
  comments:
    hypothesis: true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true
  

# Information about where the book exists on the web
repository:
  url: https://github.com/neurodata/{{cookiecutter.repo_name}}
  path_to_book: {{cookiecutter.repo_name}}
  branch: main

sphinx:
  config:
    language: en

execute: 
  execute_notebooks: off # TODO turn back on someday

bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions: #https://myst-parser.readthedocs.io/en/latest/sphinx/reference.html#sphinx-config-options
    - linkify # automatically identify “bare” web URLs and add hyperlinks
    - dollarmath
  myst_nb_output_stderr: 
    - 'remove'